export const verses = {
  Peaceful: [
    { text: "Peace I leave with you, my peace I give unto you: not as the world giveth, give I unto you. Let not your heart be troubled, neither let it be afraid.", book: "John 14:27" },
    { text: "And the peace of God, which passeth all understanding, shall keep your hearts and minds through Christ Jesus.", book: "Philippians 4:7" },
    { text: "The LORD will bless his people with peace.", book: "Psalm 29:11" },
    { text: "And let the peace of God rule in your hearts, to the which also ye are called in one body; and be ye thankful.", book: "Colossians 3:15" },
    { text: "Thou wilt keep him in perfect peace, whose mind is stayed on thee: because he trusteth in thee.", book: "Isaiah 26:3" },
    { text: "Great peace have they which love thy law: and nothing shall offend them.", book: "Psalm 119:165" },
    { text: "God is our refuge and strength, a very present help in trouble.", book: "Psalm 46:1" },
    { text: "Be of good courage, and he shall strengthen your heart, all ye that hope in the LORD.", book: "Psalm 31:24" },
    { text: "He maketh me to lie down in green pastures: he leadeth me beside the still waters.", book: "Psalm 23:2" },
    { text: "Come unto me, all ye that labour and are heavy laden, and I will give you rest.", book: "Matthew 11:28" },
    { text: "The LORD is my shepherd; I shall not want.", book: "Psalm 23:1" },
    { text: "For he shall give his angels charge over thee, to keep thee in all thy ways.", book: "Psalm 91:11" },
    { text: "Be still, and know that I am God: I will be exalted among the heathen, I will be exalted in the earth.", book: "Psalm 46:10" },
    { text: "In returning and rest shall ye be saved; in quietness and in confidence shall be your strength.", book: "Isaiah 30:15" },
    { text: "The LORD shall fight for you, and ye shall hold your peace.", book: "Exodus 14:14" },
    { text: "I will both lay me down in peace, and sleep: for thou, LORD, only makest me dwell in safety.", book: "Psalm 4:8" },
    { text: "The fruit of the Spirit is love, joy, peace, longsuffering, gentleness, goodness, faith.", book: "Galatians 5:22" },
    { text: "Now the Lord of peace himself give you peace always by all means. The Lord be with you all.", book: "2 Thessalonians 3:16" },
    { text: "And the work of righteousness shall be peace; and the effect of righteousness quietness and assurance for ever.", book: "Isaiah 32:17" },
    { text: "Blessed are the peacemakers: for they shall be called the children of God.", book: "Matthew 5:9" },
    { text: "He shall be as a tree planted by the waters, and that spreadeth out her roots by the river, and shall not see when heat cometh, but her leaf shall be green; and shall not be careful in the year of drought, neither shall cease from yielding fruit.", book: "Jeremiah 17:8" },
    { text: "The LORD is my light and my salvation; whom shall I fear? the LORD is the strength of my life; of whom shall I be afraid?", book: "Psalm 27:1" },
    { text: "For God is not the author of confusion, but of peace, as in all churches of the saints.", book: "1 Corinthians 14:33" },
    { text: "He shall feed his flock like a shepherd: he shall gather the lambs with his arm, and carry them in his bosom, and shall gently lead those that are with young.", book: "Isaiah 40:11" },
    { text: "Cast thy burden upon the LORD, and he shall sustain thee: he shall never suffer the righteous to be moved.", book: "Psalm 55:22" },
    { text: "Blessed are the pure in heart: for they shall see God.", book: "Matthew 5:8" },
    { text: "The LORD is nigh unto all them that call upon him, to all that call upon him in truth.", book: "Psalm 145:18" },
    { text: "God is our refuge and strength, a very present help in trouble.", book: "Psalm 46:1" },
    { text: "Thou wilt keep him in perfect peace, whose mind is stayed on thee.", book: "Isaiah 26:3" }
  ],

  Hopeful: [
    { text: "For I know the thoughts that I think toward you, saith the LORD, thoughts of peace, and not of evil, to give you an expected end.", book: "Jeremiah 29:11" },
    { text: "Now the God of hope fill you with all joy and peace in believing, that ye may abound in hope, through the power of the Holy Ghost.", book: "Romans 15:13" },
    { text: "Now faith is the substance of things hoped for, the evidence of things not seen.", book: "Hebrews 11:1" },
    { text: "And now, Lord, what wait I for? my hope is in thee.", book: "Psalm 39:7" },
    { text: "Blessed be the God and Father of our Lord Jesus Christ, which according to his abundant mercy hath begotten us again unto a lively hope by the resurrection of Jesus Christ from the dead.", book: "1 Peter 1:3" },
    { text: "But they that wait upon the LORD shall renew their strength; they shall mount up with wings as eagles; they shall run, and not be weary; and they shall walk, and not faint.", book: "Isaiah 40:31" },
    { text: "The LORD is good, a strong hold in the day of trouble; and he knoweth them that trust in him.", book: "Nahum 1:7" },
    { text: "For with God nothing shall be impossible.", book: "Luke 1:37" },
    { text: "Wait on the LORD: be of good courage, and he shall strengthen thine heart.", book: "Psalm 27:14" },
    { text: "Commit thy way unto the LORD; trust also in him; and he shall bring it to pass.", book: "Psalm 37:5" },
    { text: "The LORD is my portion, saith my soul; therefore will I hope in him.", book: "Lamentations 3:24" },
    { text: "Be of good courage, and he shall strengthen your heart, all ye that hope in the LORD.", book: "Psalm 31:24" },
    { text: "For we through the Spirit wait for the hope of righteousness by faith.", book: "Galatians 5:5" },
    { text: "We rejoice in hope of the glory of God.", book: "Romans 5:2" },
    { text: "Blessed is the man that trusteth in the LORD, and whose hope the LORD is.", book: "Jeremiah 17:7" },
    { text: "Thou art my hope, O Lord GOD: thou art my trust from my youth.", book: "Psalm 71:5" },
    { text: "Rejoicing in hope; patient in tribulation; continuing instant in prayer.", book: "Romans 12:12" },
    { text: "Now the God of peace, that brought again from the dead our Lord Jesus, that great shepherd of the sheep, through the blood of the everlasting covenant,", book: "Hebrews 13:20" },
    { text: "For hope maketh not ashamed; because the love of God is shed abroad in our hearts by the Holy Ghost which is given unto us.", book: "Romans 5:5" },
    { text: "But as for me, I will hope continually, and will yet praise thee more and more.", book: "Psalm 71:14" },
    { text: "The hope of the righteous shall be gladness: but the expectation of the wicked shall perish.", book: "Proverbs 10:28" },
    { text: "Blessed be the LORD, who daily loadeth us with benefits, even the God of our salvation.", book: "Psalm 68:19" },
    { text: "Let your heart retain my words: keep my commandments, and live.", book: "Proverbs 4:4" },
    { text: "The LORD hath heard my supplication; the LORD will receive my prayer.", book: "Psalm 6:9" },
    { text: "Wait on the LORD, and keep his way, and he shall exalt thee to inherit the land.", book: "Psalm 37:34" },
    { text: "Behold, God is my salvation; I will trust, and not be afraid: for the LORD JEHOVAH is my strength and my song; he also is become my salvation.", book: "Isaiah 12:2" },
    { text: "I will hope continually, and will praise thee yet more and more.", book: "Psalm 71:14" },
    { text: "The LORD is my strength and my song; he also is become my salvation.", book: "Exodus 15:2" },
    { text: "Blessed be the LORD, which daily loadeth us with benefits, even the God of our salvation.", book: "Psalm 68:19" }
  ],

  Grateful: [
    { text: "In every thing give thanks: for this is the will of God in Christ Jesus concerning you.", book: "1 Thessalonians 5:18" },
    { text: "O give thanks unto the LORD, for he is good: for his mercy endureth for ever.", book: "Psalm 107:1" },
    { text: "And whatsoever ye do in word or deed, do all in the name of the Lord Jesus, giving thanks to God and the Father by him.", book: "Colossians 3:17" },
    { text: "Giving thanks always for all things unto God and the Father in the name of our Lord Jesus Christ.", book: "Ephesians 5:20" },
    { text: "Every good gift and every perfect gift is from above, and cometh down from the Father of lights, with whom is no variableness, neither shadow of turning.", book: "James 1:17" },
    { text: "Enter into his gates with thanksgiving, and into his courts with praise: be thankful unto him, and bless his name.", book: "Psalm 100:4" },
    { text: "I will give thanks unto thee; for I am fearfully and wonderfully made: marvellous are thy works; and that my soul knoweth right well.", book: "Psalm 139:14" },
    { text: "I will praise the name of God with a song, and will magnify him with thanksgiving.", book: "Psalm 69:30" },
    { text: "Offer unto God thanksgiving; and pay thy vows unto the most High.", book: "Psalm 50:14" },
    { text: "Thanks be unto God for his unspeakable gift.", book: "2 Corinthians 9:15" },
    { text: "I will praise the LORD according to his righteousness: and will sing praise to the name of the LORD most high.", book: "Psalm 145:7" },
    { text: "The sacrifices of God are a broken spirit: a broken and a contrite heart, O God, thou wilt not despise.", book: "Psalm 51:17" },
    { text: "Bless the LORD, O my soul, and forget not all his benefits.", book: "Psalm 103:2" },
    { text: "Sing unto the LORD with thanksgiving; sing praise upon the harp unto our God.", book: "Psalm 147:7" },
    { text: "I will give thee thanks in the great congregation: I will praise thee among much people.", book: "Psalm 35:18" },
    { text: "And whatsoever ye do, do it heartily, as to the Lord, and not unto men;", book: "Colossians 3:23" },
    { text: "Be careful for nothing; but in every thing by prayer and supplication with thanksgiving let your requests be made known unto God.", book: "Philippians 4:6" },
    { text: "Blessed is he that considereth the poor: the LORD will deliver him in time of trouble.", book: "Psalm 41:1" },
    { text: "I will bless the LORD at all times: his praise shall continually be in my mouth.", book: "Psalm 34:1" },
    { text: "O give thanks unto the LORD; call upon his name: make known his deeds among the people.", book: "Psalm 105:1" },
    { text: "Praise ye the LORD. O give thanks unto the LORD; for he is good: for his mercy endureth for ever.", book: "Psalm 106:1" },
    { text: "Let them give thanks to the LORD for his mercy, and for his wonderful works to the children of men.", book: "Psalm 107:8" },
    { text: "I will praise thee with my whole heart: before the gods will I sing praise unto thee.", book: "Psalm 138:1" },
    { text: "Make a joyful noise unto the LORD, all ye lands.", book: "Psalm 100:1" },
    { text: "Give thanks unto the LORD; for he is good: for his mercy endureth for ever.", book: "Psalm 118:1" },
    { text: "Thou art my God; I will exalt thee, I will praise thy name; for thou hast done wonderful things; thy counsels of old are faithfulness and truth.", book: "Psalm 118:28" },
    { text: "Rejoice evermore. Pray without ceasing. In every thing give thanks.", book: "1 Thessalonians 5:16-18" },
    { text: "Sing unto the LORD, O ye saints of his, and give thanks at the remembrance of his holiness.", book: "Psalm 30:4" }
  ],

  Anxious: [
    { text: "Casting all your care upon him; for he careth for you.", book: "1 Peter 5:7" },
    { text: "Take therefore no thought for the morrow: for the morrow shall take thought for the things of itself. Sufficient unto the day is the evil thereof.", book: "Matthew 6:34" },
    { text: "Be careful for nothing; but in every thing by prayer and supplication with thanksgiving let your requests be made known unto God.", book: "Philippians 4:6" },
    { text: "Cast thy burden upon the LORD, and he shall sustain thee: he shall never suffer the righteous to be moved.", book: "Psalm 55:22" },
    { text: "Let not your heart be troubled: ye believe in God, believe also in me.", book: "John 14:1" },
    { text: "Come unto me, all ye that labour and are heavy laden, and I will give you rest.", book: "Matthew 11:28" },
    { text: "The LORD is nigh unto them that are of a broken heart; and saveth such as be of a contrite spirit.", book: "Psalm 34:18" },
    { text: "God is our refuge and strength, a very present help in trouble.", book: "Psalm 46:1" },
    { text: "Peace I leave with you, my peace I give unto you: not as the world giveth, give I unto you.", book: "John 14:27" },
    { text: "The LORD is my light and my salvation; whom shall I fear? the LORD is the strength of my life; of whom shall I be afraid?", book: "Psalm 27:1" },
    { text: "Fear thou not; for I am with thee: be not dismayed; for I am thy God: I will strengthen thee; yea, I will help thee; yea, I will uphold thee with the right hand of my righteousness.", book: "Isaiah 41:10" },
    { text: "The LORD shall fight for you, and ye shall hold your peace.", book: "Exodus 14:14" },
    { text: "Commit thy way unto the LORD; trust also in him; and he shall bring it to pass.", book: "Psalm 37:5" },
    { text: "For God hath not given us the spirit of fear; but of power, and of love, and of a sound mind.", book: "2 Timothy 1:7" },
    { text: "When I am afraid, I will trust in thee.", book: "Psalm 56:3" },
    { text: "Thou wilt keep him in perfect peace, whose mind is stayed on thee.", book: "Isaiah 26:3" },
    { text: "The angel of the LORD encampeth round about them that fear him, and delivereth them.", book: "Psalm 34:7" },
    { text: "The LORD is good, a strong hold in the day of trouble; and he knoweth them that trust in him.", book: "Nahum 1:7" },
    { text: "He healeth the broken in heart, and bindeth up their wounds.", book: "Psalm 147:3" },
    { text: "Thou art my refuge and my shield: I hope in thy word.", book: "Psalm 119:114" },
    { text: "I sought the LORD, and he heard me, and delivered me from all my fears.", book: "Psalm 34:4" },
    { text: "God is our refuge and strength, a very present help in trouble.", book: "Psalm 46:1" },
    { text: "Casting all your care upon him; for he careth for you.", book: "1 Peter 5:7" },
    { text: "Blessed is the man that trusteth in the LORD, and whose hope the LORD is.", book: "Jeremiah 17:7" },
    { text: "Trust in the LORD with all thine heart; and lean not unto thine own understanding.", book: "Proverbs 3:5" },
    { text: "The LORD is my rock, and my fortress, and my deliverer; my God, my strength, in whom I will trust; my buckler, and the horn of my salvation, and my high tower.", book: "Psalm 18:2" },
    { text: "He shall cover thee with his feathers, and under his wings shalt thou trust: his truth shall be thy shield and buckler.", book: "Psalm 91:4" },
    { text: "Be not afraid of sudden fear, neither of the desolation of the wicked, when it cometh.", book: "Proverbs 3:25" },
    { text: "The LORD is nigh unto all them that call upon him, to all that call upon him in truth.", book: "Psalm 145:18" }
  ]
};
